# Generated by Django 4.1.1 on 2022-11-20 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='time_stamp',
            new_name='replied_date',
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='comment_reply',
            new_name='reply_comment',
        ),
        migrations.RenameField(
            model_name='replycomment',
            old_name='text_reply',
            new_name='reply_content',
        ),
        migrations.RemoveField(
            model_name='replycomment',
            name='name_reply',
        ),
        migrations.AddField(
            model_name='replycomment',
            name='replier_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
